"""Image_segmentation_using_mean_shift.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QcBT1ABW165aAR54uDrJHyD6H4vkqiom
"""

!pip install --upgrade git+https://github.com/anirekhj/pymeanshift.git@1ba90da647342184ea7df378d7f21eba257a51d9

from PIL import Image
import pymeanshift as pms
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import requests
from io import BytesIO

# Any image from the web can be used!
response = requests.get("https://i.imgur.com/YN1uROV.jpg")
original_image = Image.open(BytesIO(response.content))

(segmented_image, labels_image, number_regions) = pms.segment(original_image, spatial_radius=6,
                                                              range_radius=4.5, min_density=50)

plt.figure(0)
plt.imshow(original_image)
plt.title("Original Image")
plt.axis('off')

plt.figure(1)
plt.imshow(segmented_image)
plt.title("Segmented Image")
plt.axis('off')

plt.show()

print("Total Clusters: "+str(number_regions))
